language: python

python:
  - "2.7.13"

before_install:
  - pip install --upgrade setuptools

install:
  - pip install -r requirements.txt

script: python tests/*

notifications:
  email:
    on_success: never
    on_failure: always